version: 2.1
commands:
  destroy_environment:
    parameters:
      when_to_run:
        type: string
        default: "on_fail"
    steps:
      - run:
          name: Destroy Environments
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
              --region=us-east-1 

      - run: return 1
      - destroy_environment     

workflows:
  my_workflow:
    jobs:
      - create_infrastructure:
          context:
            - AWSPolicy